{% set name = "gilknocker" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # FIXME no pypi tarball available https://github.com/milesgranger/gilknocker/issues/32
  # url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gilknocker-{{ version }}.tar.gz
  # sha256:
  git_url: https://github.com/milesgranger/gilknocker
  git_rev: 81f2bc6f6ec865a1c98f70a73aa5197f3d537bde  # v0.4.2

build:
  number: 0
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - toml                                   # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}                    # [unix]
    - {{ stdlib("c") }}                      # [unix]
    - clang                                  # [win]
  host:
    - python
    - pip
    - maturin >=1.3.0,<2.0.0
    - toml
  run:
    - python

test:
  imports:
    - gilknocker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/milesgranger/gilknocker
  summary: Knock on the Python GIL, determine how busy it is.
  license: MIT AND Unlicense
  license_file:
    - LICENSE-MIT
    - LICENSE

extra:
  recipe-maintainers:
    - milesgranger
